export default [
  {
    title: 'Dashboard',
    icon: { icon: 'ri-home-smile-line' },
    to: 'root',
    action: 'read',
    subject: 'Dashboard',
  },
  { heading: 'Content' },
  {
    title: 'Categories',
    icon: { icon: 'ri-price-tag-3-line' },
    to: 'categories-listing',
    action: 'read',
    subject: 'Categories',
  },
  {
    title: 'Articles',
    icon: { icon: 'ri-newspaper-line' },
    to: 'articles-listing',
    action: 'read',
    subject: 'Articles',
  },
  { heading: 'Digest' },
  {
    title: 'Digest',
    icon: { icon: 'ri-mail-send-line' },
    action: 'read',
    subject: 'Digest',
    children: [
      { title: 'Today',    to: 'digest-listing',  action: 'read',   subject: 'Digest' },
      { title: 'Settings', to: 'digest-settings', action: 'update', subject: 'Digest' },
    ],
  },
  { heading: 'Account' },
  {
    title: 'Preferences',
    icon: { icon: 'ri-settings-3-line' },
    to: 'preferences',
    action: 'read',
    subject: 'Preferences',
  },
  { heading: 'Administration' },
  {
    title: 'Settings',
    icon: { icon: 'ri-shield-keyhole-line' },
    to: 'settings',
    action: 'manage',
    subject: 'Settings',
  },
]
